// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://exhmtishhyaaqerjqugi.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImV4aG10aXNoaHlhYXFlcmpxdWdpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM3MTU4ODAsImV4cCI6MjA2OTI5MTg4MH0.Pn5-6xtpXdvNoP8hlI3qiSqmqcm3mNtTFMHtNXLU4sM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});